server:
  port: 8081

spring:
  application:
    name: productos-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/productos_db}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
